import { Hono } from "hono";
import type { Env, AuthedUser } from "../env";
import { requireAuth, requireRole } from "../auth";
import { getSupabaseAdmin } from "../supabaseAdmin";
import { hashPassword, generateTempPassword } from "../crypto";

export const doctor = new Hono<{ Bindings: Env }>();

// Every route here is doctor-only.
doctor.use("*", requireAuth);
doctor.use("*", requireRole("doctor"));

function toWhatsAppDigits(phone: string): string {
  return phone.replace(/[^\d]/g, "");
}

function buildWhatsAppLink(phone: string, message: string): string {
  return `https://wa.me/${toWhatsAppDigits(phone)}?text=${encodeURIComponent(message)}`;
}

function isValidEmail(email: string): boolean {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
}

/**
 * POST /api/doctor/patients
 * Creates a patient account on the patient's behalf (for someone who hasn't
 * self-signed-up). Generates a readable temporary password, stores ONLY its
 * PBKDF2 hash with `must_change_password=true`, and returns the plaintext
 * password exactly once so the doctor can deliver it via WhatsApp.
 */
doctor.post("/patients", async (c) => {
  const body = await c.req.json<{ full_name?: string; email?: string; phone?: string }>();
  const email = body.email?.trim().toLowerCase();
  const fullName = body.full_name?.trim();
  const phone = body.phone?.trim() || null;

  if (!fullName) return c.json({ error: "full_name is required" }, 400);
  if (!email || !isValidEmail(email)) return c.json({ error: "A valid email is required" }, 400);

  const supabase = await getSupabaseAdmin(c.env);

  const { data: existing } = await supabase
    .from("users")
    .select("id")
    .eq("email", email)
    .maybeSingle();
  if (existing) return c.json({ error: "An account with this email already exists" }, 409);

  const tempPassword = generateTempPassword();
  const passwordHash = await hashPassword(tempPassword);
  const id = crypto.randomUUID();

  const { data: user, error: userErr } = await supabase
    .from("users")
    .insert({
      id,
      role: "patient",
      full_name: fullName,
      email,
      phone,
      password_hash: passwordHash,
      must_change_password: true,
    })
    .select("id, role, email, full_name, phone, avatar_url, must_change_password")
    .single();
  if (userErr) {
    console.error("doctor.createPatient: insert failed", userErr.message);
    return c.json({ error: userErr.message }, 500);
  }

  const { error: patientsErr } = await supabase.from("patients").insert({ user_id: id });
  if (patientsErr) console.error("doctor.createPatient: patients insert failed", patientsErr.message);

  return c.json({ user, temp_password: tempPassword }, 201);
});

/**
 * POST /api/doctor/patients/:id/regenerate-password
 * Issues a fresh temporary password for an existing patient (forgot / resend),
 * sets `must_change_password=true`, and returns the plaintext password once.
 * The original password is never revealed or recoverable.
 */
doctor.post("/patients/:id/regenerate-password", async (c) => {
  const id = c.req.param("id");
  const supabase = await getSupabaseAdmin(c.env);

  const { data: existing, error } = await supabase
    .from("users")
    .select("id, role")
    .eq("id", id)
    .maybeSingle();
  if (error || !existing) return c.json({ error: "Patient not found" }, 404);
  if (existing.role !== "patient") return c.json({ error: "Not a patient account" }, 400);

  const tempPassword = generateTempPassword();
  const passwordHash = await hashPassword(tempPassword);

  const { error: updateErr } = await supabase
    .from("users")
    .update({ password_hash: passwordHash, must_change_password: true })
    .eq("id", id);
  if (updateErr) {
    console.error("doctor.regeneratePassword: update failed", updateErr.message);
    return c.json({ error: updateErr.message }, 500);
  }

  return c.json({ temp_password: tempPassword });
});

/**
 * GET /api/doctor/reminders
 * Lists pending (unsent) WhatsApp reminder links generated by the daily cron,
 * joined with the appointment + patient so the doctor knows who each is for.
 */
doctor.get("/reminders", async (c) => {
  const supabase = await getSupabaseAdmin(c.env);

  const { data, error } = await supabase
    .from("pending_whatsapp_reminders")
    .select("*, appointments(starts_at, ends_at, visit_address, users!appointments_patient_id_fkey(full_name, phone))")
    .is("sent_at", null)
    .order("created_at", { ascending: false });
  if (error) return c.json({ error: error.message }, 500);

  return c.json({ reminders: data ?? [] });
});

/** POST /api/doctor/reminders/:id/mark-sent — flags a reminder as sent. */
doctor.post("/reminders/:id/mark-sent", async (c) => {
  const id = c.req.param("id");
  const supabase = await getSupabaseAdmin(c.env);

  const { data: updated, error } = await supabase
    .from("pending_whatsapp_reminders")
    .update({ sent_at: new Date().toISOString() })
    .eq("id", id)
    .select()
    .single();
  if (error) return c.json({ error: error.message }, 500);

  return c.json({ reminder: updated });
});

/**
 * POST /api/doctor/reminders/:id/whatsapp-link
 * (Re)builds a click-to-chat link for an existing reminder so the doctor can
 * re-open WhatsApp if the stored link is stale. Kept minimal on purpose.
 */
doctor.post("/reminders/:id/whatsapp-link", async (c) => {
  const id = c.req.param("id");
  const supabase = await getSupabaseAdmin(c.env);

  const { data: reminder, error } = await supabase
    .from("pending_whatsapp_reminders")
    .select("*, appointments(starts_at, users!appointments_patient_id_fkey(full_name, phone))")
    .eq("id", id)
    .maybeSingle();
  if (error || !reminder) return c.json({ error: "Reminder not found" }, 404);

  const info = reminder.appointments as unknown as {
    starts_at: string;
    users: { full_name: string; phone: string | null };
  };
  if (!info?.users?.phone) return c.json({ error: "Patient has no phone number on file" }, 400);

  const message =
    `Hi ${info.users.full_name}, a reminder about your Neuro TeleRehab session on ` +
    `${formatSlot(info.starts_at)}. Reply here if you need to reschedule.`;
  return c.json({ whatsapp_url: buildWhatsAppLink(info.users.phone, message) });
});

export function formatSlot(startsAt: string): string {
  return new Date(startsAt).toLocaleString("en-IN", {
    weekday: "short", day: "numeric", month: "short", hour: "numeric", minute: "2-digit",
  });
}